<a href="https://colab.research.google.com/github/urvesh2012/MLTSA25_UBhagat/blob/main/MLTSA_WK2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
my_str="Hello"


In [2]:
my_str

'Hello'

In [3]:
print(my_str)

Hello


In [8]:
my_int=6

In [9]:
my_float=6.

In [10]:
print(my_float)

6.0


In [11]:
my_int*my_float

36.0

In [12]:
my_int*my_str

'HelloHelloHelloHelloHelloHello'

In [14]:
import numpy as np


In [17]:
helloworld="Hello" + " World!"
helloworld

'Hello World!'

In [18]:
my_nparr=np.array([1,2,3])
my_nparr

array([1, 2, 3])

In [19]:
my_int*my_nparr

array([ 6, 12, 18])

In [20]:
my_bool= True

In [21]:
my_int==6

True

In [23]:
my_int != 6

False

In [24]:
if my_int == 6:
    print("my_int is 6")
else:
  print("my_int is not 6")

my_int is 6


In [25]:
type(my_int)

int

In [27]:
my_nparr.dtype

dtype('int64')

In [28]:
my_nparr.max()

3

In [29]:
my_nparr.argmax()

2

In [30]:
my_nparr[2]

3

In [31]:
my_nparr[1:]

array([2, 3])

In [33]:
list(range(1,4))

[1, 2, 3]

In [35]:
for a in range(1,4):
    print(sum(np.arange(0,a)))

0
1
3


In [37]:
np.arange(0,a)

array([0, 1, 2])

In [38]:
def allodds(n):
  """
  Prints all odd numbers between 0 and n
  Input: n
  Output: all odd numbers between 0 and n
  """

  return [x for x in range(0,n+1) if x%2==1]



In [39]:
allodds(10)

[1, 3, 5, 7, 9]

In [40]:
allodds?

In [46]:
def pel(s):
  if type(s)!=str:
    return "Not a string"
  s=s.lower()
  s1=s[::-1]
  if s==s1:
    return True
  else:
    return False

In [47]:
pel("aoa")

True

In [48]:
pel(7)

'Not a string'

In [49]:
def ispel(s):
  assert type(s)==str, "is Not a String"

In [50]:
ispel(7)

AssertionError: is Not a String